### ISSUE TITLE
I use column-calculation not show result 

### ISSUE THREAD

**Issue by wphatpat** [koalyptus/TableFilter#517]
I use extension : column calculations as [http://koalyptus.github.io/TableFilter/column-calculations.html](url) it's not show result and I try inspect console it's return
`Uncaught TypeError: Cannot read property 'cellIndex' of undefined
    at t.value (https://unpkg.com/tablefilter@0.5.42/dist/tablefilter/tablefilter.js:7:61562)
    at https://unpkg.com/tablefilter@0.5.42/dist/tablefilter/tablefilter.js:7:65313
    at Array.map (native)
    at t.value (https://unpkg.com/tablefilter@0.5.42/dist/tablefilter/tablefilter.js:7:65290)
    at t.value (https://unpkg.com/tablefilter@0.5.42/dist/tablefilter/tablefilter.js:7:64308)
    at e.value (https://unpkg.com/tablefilter@0.5.42/dist/tablefilter/tf-0-13c8536aa827812750aa.js:7:18272)
    at t.<anonymous> (https://unpkg.com/tablefilter@0.5.42/dist/tablefilter/tf-0-13c8536aa827812750aa.js:7:17807)
    at t.value (https://unpkg.com/tablefilter@0.5.42/dist/tablefilter/tablefilter.js:7:73622)
    at t.value (https://unpkg.com/tablefilter@0.5.42/dist/tablefilter/tablefilter.js:7:56849)
    at e.value (https://unpkg.com/tablefilter@0.5.42/dist/tablefilter/tablefilter.js:7:147806)`

**Comment by koalyptus** [comment]
@wphatpat provide more context, I suggest to follow https://github.com/koalyptus/TableFilter/blob/master/CONTRIBUTING.md

**Comment by wphatpat** [comment]
now it's work fine , thanks!
